### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.fasterxml.jackson.core:jackson-core:jar

### ISSUE THREAD

**Issue by Bing-ok** [yahoo/yql-plus#118]
## Issue description
Hi, there are multiple versions of **_com.fasterxml.jackson.core:jackson-core_** in **_yql-plus-master(language module)_**. As shown in the following dependency tree, library **_com.fasterxml.jackson.core:jackson-core:2.9.10_** is transitively introduced by **_com.fasterxml.jackson.core:jackson-databind:2.9.10.3_**, but has been managed to be version **_2.7.9_**.

However, several methods defined in shadowed version **_com.fasterxml.jackson.core:jackson-core:2.9.10_** are referenced by client project via **_com.fasterxml.jackson.core:jackson-databind:2.9.10.3_**, but missing in the actually loaded version **_com.fasterxml.jackson.core:jackson-core:2.7.9_**.

For instance, the following missing methods(defined in **_com.fasterxml.jackson.core:jackson-core:2.9.10_**) are actually referenced by **_yql-plus-master(language module)_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_yql-plus-master(language module)_**.

**_1. com.fasterxml.jackson.core.JsonGenerator: void writeFieldId(long)_** is invoked by **_yql-plus-master(language module)_** via the following path:
<pre><code>
paths------
&lt;com.yahoo.yqlplus.language.operator.JsonOperatorDump$ProgramDumpModule$1: void serialize(com.yahoo.yqlplus.language.operator.OperatorNode,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; yql-plus-master\yqlplus_language\target\classes
fasterxml.jackson.databind.SerializerProvider: void defaultSerializeValue(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.StdKeySerializers$Default: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: void writeFieldId(long)&gt;
</code></pre>

**_2. com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypeSuffix(com.fasterxml.jackson.core.type.WritableTypeId)_** is invoked by **_yql-plus-master(language module)_** via the following path:
<pre><code>
paths------
&lt;com.yahoo.yqlplus.language.operator.JsonOperatorDump$ProgramDumpModule$1: void serialize(com.yahoo.yqlplus.language.operator.OperatorNode,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; yql-plus-master\yqlplus_language\target\classes
&lt;com.fasterxml.jackson.databind.SerializerProvider: void defaultSerializeValue(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.impl.UnknownSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase: com.fasterxml.jackson.core.type.WritableTypeId writeTypeSuffix(com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.core.type.WritableTypeId)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypeSuffix(com.fasterxml.jackson.core.type.WritableTypeId)&gt;
</code></pre>

**_3. com.fasterxml.jackson.core.JsonGenerator: void writeEmbeddedObject(java.lang.Object)_** is invoked by **_yql-plus-master(language module)_** via the following path:
<pre><code>
paths------
&lt;com.yahoo.yqlplus.language.operator.JsonOperatorDump$ProgramDumpModule$1: void serialize(com.yahoo.yqlplus.language.operator.OperatorNode,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; yql-plus-master\yqlplus_language\target\classes
&lt;com.fasterxml.jackson.databind.SerializerProvider: void defaultSerializeValue(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.TokenBufferSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.TokenBufferSerializer: void serialize(com.fasterxml.jackson.databind.util.TokenBuffer,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.util.TokenBuffer: void serialize(com.fasterxml.jackson.core.JsonGenerator)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: void writeEmbeddedObject(java.lang.Object)>
</code></pre>

**_4. com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.type.WritableTypeId)_** is invoked by **_yql-plus-master(language module)_** via the following path:
<pre><code>
paths------
&lt;com.yahoo.yqlplus.language.operator.JsonOperatorDump$ProgramDumpModule$1: void serialize(com.yahoo.yqlplus.language.operator.OperatorNode,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; yql-plus-master\yqlplus_language\target\classes
&lt;com.fasterxml.jackson.databind.SerializerProvider: void defaultSerializeValue(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.impl.UnknownSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.core.type.WritableTypeId)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.type.WritableTypeId)&gt;
</code></pre>

**_5. com.fasterxml.jackson.core.JsonpCharacterEscapes: com.fasterxml.jackson.core.JsonpCharacterEscapes instance()_** is invoked by **_yql-plus-master(language module)_** via the following path:
<pre><code>
paths------
&lt;com.yahoo.yqlplus.language.operator.JsonOperatorDump: java.lang.String dump(com.yahoo.yqlplus.language.operator.OperatorNode)&gt; yql-plus-master\yqlplus_language\target\classes
&lt;com.fasterxml.jackson.databind.ObjectWriter: java.lang.String writeValueAsString(java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ObjectWriter: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ObjectWriter$Prefetch: void serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.ser.DefaultSerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializePolymorphic(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.JsonSerializer,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.JsonValueSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.SerializableSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.ser.std.SerializableSerializer: void serialize(com.fasterxml.jackson.databind.JsonSerializable,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.databind.util.JSONPObject: void serialize(com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.9.10.3\jackson-databind-2.9.10.3.jar
&lt;com.fasterxml.jackson.core.JsonpCharacterEscapes: com.fasterxml.jackson.core.JsonpCharacterEscapes instance()&gt;
</code></pre>

## Suggested fixing solutions
Declare a direct dependency **_com.fasterxml.jackson.core:jackson-core:2.9.10_** in the pom file of **_yql-plus-master(language module)_**, to override **_com.fasterxml.jackson.core:jackson-core_**'s managed version.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.yahoo.yqlplus:yqlplus_language:jar:1.0.16
[INFO] +- org.testng:testng:jar:6.8.5:test
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:test
[INFO] |  +- com.beust:jcommander:jar:1.27:test
[INFO] |  \- org.yaml:snakeyaml:jar:1.6:test
[INFO] +- org.antlr:antlr4-runtime:jar:4.5:compile
[INFO] |  \- org.abego.treelayout:org.abego.treelayout.core:jar:1.0.1:compile
[INFO] +- com.google.guava:guava:jar:24.1.1-jre:compile
[INFO] |  +- (com.google.code.findbugs:jsr305:jar:1.3.9:compile - omitted for conflict with 2.0.1)
[INFO] |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:2.0.1:provided (scope not updated to compile)
[INFO] +- com.google.inject:guice:jar:4.0:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- (com.google.guava:guava:jar:24.1.1-jre:compile - version managed from 16.0.1; omitted for duplicate)
[INFO] +- <b>com.fasterxml.jackson.core:jackson-core:jar:2.7.9:compile</b>
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.3:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile
[INFO]    \- <b>(com.fasterxml.jackson.core:jackson-core:jar:2.7.9:compile - version managed from 2.9.10; omitted for duplicate)</b>
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @dsyzhu

**Comment by Bing-ok** [comment]
@daisyzhu Could you please help me review this issue? Thank you very much.

**Comment by dsyzhu** [comment]
ok
