### ISSUE TITLE
Non-constant Map expression can't have key which is not a valid Java variable name

### ISSUE THREAD

**Issue by dsyzhu** [yahoo/yql-plus#64]
when compiling program:

PROGRAM();
SELECT * FROM mapsource({'a.b.c':'abc'}) WHERE id = 2 OUTPUT AS out;

got

java.lang.IllegalArgumentException: Invalid name (must be a valid unqualified name): a.b.c
at org.objectweb.asm.util.CheckMethodAdapter.checkUnqualifiedName(Unknown Source)
at org.objectweb.asm.util.CheckMethodAdapter.visitFieldInsn(Unknown Source)

**Comment by dsyzhu** [comment]
when compiling program:

```
PROGRAM();
SELECT * FROM mapsource({'a.b.c':'abc'}) WHERE id = 2 OUTPUT AS out;
```

got 
```
java.lang.IllegalArgumentException: Invalid name (must be a valid unqualified name): a.b.c
at org.objectweb.asm.util.CheckMethodAdapter.checkUnqualifiedName(Unknown Source)
at org.objectweb.asm.util.CheckMethodAdapter.visitFieldInsn(Unknown Source)
```

**Comment by xythian** [comment]
This raises a separate question: why didn't that expression compile the map `({'a.b.c':'abc'}` as a constant? It's good in the sense that we caught the bug in map expressions, but it means there may be another bug.

**Comment by dsyzhu** [comment]
My bad. The example was wrong. It won't cause the problem since that map will be compiled to constant map. Won't go to the code path to build a Record.

The following is the one causing the problem:
```
PROGRAM (@count int32 = 15);
SELECT * FROM mapsource({'a.b.c': 'abc', 'a' : @count}) WHERE id = 2 OUTPUT AS out;
```
